name: build llvm

on:
  push:
    # branches: [ master ]
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches: [ master ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-18.04', 'macos-latest']
      fail-fast: false

    steps:
      - name: Checkout
        working-directory: .
        run: |
          git clone --depth 1 -b codon https://github.com/exaloop/llvm-project
          cmake -S llvm-project/llvm -B llvm-project/build -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DLLVM_INCLUDE_TESTS=OFF \
              -DLLVM_ENABLE_RTTI=ON \
              -DLLVM_ENABLE_ZLIB=OFF \
              -DLLVM_ENABLE_TERMINFO=OFF \
              -DLLVM_TARGETS_TO_BUILD=all
          cmake --build llvm-project/build
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build llvm
        working-directory: llvm-project
        run: |
          tar -czf llvm-build-${{ matrix.os }}.tar.gz build
      - name: release-llvm
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            llvm-project/llvm-build-${{ matrix.os }}.tar.gz
