name: build llvm

on:
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: ['windows-latest', 'ubuntu-18.04', 'ubuntu-latest', 'macos-latest']
        os: ['ubuntu-18.04']
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Build llvm
        run: |
          make llvm-build
          tar -czf llvm-build-${{ matrix.os }}.tar.gz llvm-build
      - name: release-llvm
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            llvm-build-${{ matrix.os }}.tar.gz
